apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
  labels:
    app: hello-app 
spec:
  selector:
    app: hello-app 

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer