apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-hello-app-service
  labels:
    app: hello-app 
spec:
  selector:
    app: hello-app 

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer